export const data=[
    {
        id:1,
        img:'https://www.aimwaytours.com/pagegallery/pokhara-city-full-day-tour16.jpeg',
        name:'Pokhara',
    },
    {
        id:2,
        img:'https://www.breakfreeadventures.com/wp-content/uploads/Chitwan-National-Park-Tour-1.jpg',
        name:'Chitwan',
    },
    {
        id:3,
        img:'https://nepaltourismhub.com/illion-asset/uploads/2020/01/butwal-1.jpg',
        name:'Butwal',
    },
    {
        id:4,
        img:'https://i0.wp.com/imfreee.com/wp-content/uploads/2021/02/Exploring-Besisahar-Lamjung-Nepal-scaled.jpg?ssl=1',
        name:'Besisahar',
    },
    {
        id:5,
        img:'https://farm8.staticflickr.com/7576/16127448190_159b0b4065_o.jpg',
        name:'Manang',
    },
    {
        id:6,
        img:'https://assets.rumsan.com/clients/recordnepal/QmUYJRBTPvHVuvtcz4Lz86TUzp43PCyWQTwcnALuxDkfAg',
        name:'Bhairawa ',
    },
    {
        id:7,
        img:'https://nepaltourismhub.com/illion-asset/uploads/2020/01/butwal-1.jpg',
        name:'Butwal',
    },
    {
        id:8,
        img:'https://tigerencounter.com/wp-content/uploads/2019/11/Langtang-National-Park.jpg',
        name:'langtang',
    },
    {
        id:9,
        img:'https://fulltimeexplorer.com/wp-content/uploads/2019/06/The-Rani-Mahal-Tansen-Palpa-Nepal-1-1.jpg',
        name:'Palpa',
    },
    
]